version: '4.32.0'
services:
  php:
    image: php:8.2-apache 
    container_name: php8.2
    ports:
      - 8000:80
    volumes:
        - ./php:/var/www/html/
    build:
      context: .
      dockerfile: Dockerfile
  db:
    image: mysql:8.0
    container_name: mysql8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: J25061984c%
      MYSQL_DATABASE: arcadia
      MYSQL_USER: jeAn-phI
      MYSQL_PASSWORD: J25061984c%#
    ports:
      - 3305:3000
      
      
  mongodb:
    image: mongo:7.0.8
    restart: always
    ports:
      - 8090:27017
    environment:  
      MONGO_INITDB_ROOT_USERNAME: jean-phi
      MONGO_INITDB_ROOT_PASSWORD: J25061984c

